export const FETCH_PROCESS_START = 'FETCH_PROCESS_START'
export const FETCH_PROCESS_SUCSSES = 'FETCH_PROCESS_SUCSSES'
export const FETCH_PROCESS_ERROR = 'FETCH_PROCESS_ERROR'

export const CREATE_NEW_USER = 'CREATE_NEW_USER'