export const FETCH_PROCESS_LOADING = 'FETCH_PROCESS_LOADING'
export const FETCH_PROCESS_SUCSSES = 'FETCH_PROCESS_SUCSSES'
export const FETCH_PROCESS_ERROR = 'FETCH_PROCESS_ERROR'

export const AUTH_SUCCES = "AUTH_SUCCES"

export const EDIT_USER_DATA_SUCCES = "EDIT_USER_DATA_SUCCES"